learning_log/urls.py
from django.contrib import admin
from django.urls import path , include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('',include('learning_logs.urls')),
]

learning_logs/urls.py
'''Определяет схемы URL для learning_logs'''
from django.urls import path
from . import views

app_name = 'learning_logs'
urlpatterns = [
    # Домашняя страница
    path('', views.index, name='index'),
    # Страница со списком всех тем.
    path('topics/', views.topics, name='topics'),
    # Страница с подробной информацией по отдельной теме
    path('topics/<int:topic_id>/', views.topic, name = 'topic'),
    # Страница для добавления новой темы
    path('new_topic/', views.new_topic, name = 'new_topic'),
    # Страница для добавления новой записи
    path('new_entry/<int:topic_id>/', views.new_entry, name='new_entry'),
    # Страница для редактирования записи
    path('edit_entry/<int:entry_id>/', views.edit_entry, name='edit_entry'),
]

users/urls.py
"""Определяет схемы URL для пользователей"""
from django.urls import path, include
from . import views

app_name = 'users'
urlpatterns = [
    # Включить URL авторизации по умолчанию.
    path('', include('django.contrib.auth.urls')),
    # Страница регистрации.
    path('register/', views.register, name='register'),
]

learning_logs/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Topic(models.Model):
    # Тема которую изучает пользователь
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        #Возвращает строковое представление модели.
        return self.text

class Entry(models.Model):
    # Информация , изученная пользователем по теме
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'entries'
    def __str__(self):
        # Возвращает строковое представление модели
        if len(self.text) > 50:
            return f"{self.text[:50]}..."
        else:
            return self.text

users/models.py
from django.db import models

# Create your models here.

learning_logs/views.py
from django.shortcuts import render , redirect
from django.contrib.auth.decorators import login_required
from django.http import Http404
from .models import Topic , Entry
from .froms import TopicForm , EntryForm


def index(request):
    # Домашняя страница
    return render(request, 'learning_logs/index.html')
    
@login_required    
def topics(request):
    '''Выводит список тем'''
    topics = Topic.objects.filter(owner=request.user).order_by('date_added')
    context = {'topics': topics}
    return render(request, 'learning_logs/topics.html', context)

@login_required
def topic(request, topic_id):
    '''Выводит одну тему и все ее записи.'''
    topic = Topic.objects.get(id=topic_id)
    # Проверка того, что тема принадлежит текущему пользователю.
    if topic.owner != request.user:
        raise Http404

    entries = topic.entry_set.order_by('-date_added')
    context = {'topic' : topic, 'entries' : entries}
    return render(request,'learning_logs/topic.html', context)

@login_required
def new_topic(request):
    '''Определяет новую тему.'''
    if request.method != 'POST':
        # Данные не отправились, создается пустая форма.
        form = TopicForm()
    else:
        # Отправлены данные POST; обработать данные.
        form = TopicForm(data = request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
            return redirect('learning_logs:topics')
    # Вывести пустую или недействительную форму.
    context = {'form' : form}
    return render(request, 'learning_logs/new_topic.html',context)

@login_required
def new_entry(request , topic_id):
    '''Добавляет новую запись по конкретной теме.'''
    topic = Topic.objects.get(id=topic_id)
    if request.method != 'POST':
        # Данные не отправились, создается пустая форма.
        form = EntryForm()
    else:
        # Отправлены данные POST; обработать данные.
        form = EntryForm(data = request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return redirect('learning_logs:topic', topic_id=topic_id)
    # Вывести пустую или недействительную форму.
    context = {'topic' : topic, 'form': form}
    return render(request, 'learning_logs/new_entry.html',context)

@login_required
def edit_entry(request , entry_id):
    '''Редактирует существующую запись'''
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    if topic.owner != request.user:
        raise Http404

    if request.method != 'POST':
        # Исходный запрос; форма заполняется данными текущей записи.
        form = EntryForm(instance=entry)
    else:
        # Отправка данных POST; обработать данные.
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('learning_logs:topic', topic_id=topic.id)
    # Вывести пустую или недействительную форму.
    context = {'entry' : entry, 'topic': topic, 'form': form}
    return render(request, 'learning_logs/edit_entry.html',context)

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login

def register(request):
    """Регистрирует нового пользователя."""
    if request.method != 'POST':
        # Выводит пустую форму регистрации.
        form = UserCreationForm()
    else:
        # Обработка заполненной формы.
        form = UserCreationForm(data=request.POST)

        if form.is_valid():
            new_user = form.save()
            # Выполнение входа и перенаправления на домашнюю страницу
            login(request, new_user)
            return redirect('learning_logs:index')
    
    # Вывести пустую или недействительную форму.
    context = {'form': form}
    return render(request, 'users/register.html', context)

learning_logs/templates/learning_logs/base.html
<p>
    <a href="{% url 'learning_logs:index' %}">Журнал обучения</a>
    <a href="{% url 'learning_logs:topics' %}">Темы</a>
    {% if user.is_authenticated %}
       Привет, {{ user.username }}.
       <form id="logout-form" action="{% url 'users:logout' %}" method="post" style="display:inline;">
        {% csrf_token %}
        <button type="submit" style="background:none;border:none;padding:0;color:blue;cursor:pointer;">
            Выйти
        </button>
    </form>
    {% else %}
    <a href="{% url 'users:register' %}">Зарегистрироваться</a>
    <a href="{% url 'users:login' %}">Авторизоваться</a>
    {% endif %}

</p>
{% block content %}{% endblock content %}

learning_logs/templates/learning_logs/edit_entry.html
{% extends "Learning_Logs/base.html" %}

{% block content %}

<p><a href ="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></p>

<p>Редактировать запись:</p>
<form action="{% url 'learning_logs:edit_entry' entry.id %}" method='post'>
    {% csrf_token %}
    {{ form.as_p }}
    <button type ="submit">сохранить изменения</button>
</form>

{% endblock content %}

learning_logs/templates/learning_logs/index.html
{% extends "Learning_Logs/base.html" %}
{% block content%}

<p>Журнал обучения помогает вам отслеживать ваше обучение, на любую тему вы 
    узнав про.
</p>
{% endblock content %}

learning_logs/templates/learning_logs/new_entry.html
{% extends "Learning_Logs/base.html" %}

{% block content %}

<p><a href ="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></p>

<p>Добавить новую запись:</p>
<form action="{% url 'learning_logs:new_entry' topic.id %}" method='post'>
    {% csrf_token %}
    {{ form.as_p }}
    <button type ="submit">добавить запись</button>
</form>

{% endblock content %}

learning_logs/templates/learning_logs/new_topic.html
{% extends "Learning_Logs/base.html" %}

{% block content %}

<p>Добавьте новую тему:</p>

<form action="{% url 'learning_logs:new_topic' %}" method='post'>
    {% csrf_token %}
    {{ form.as_p }}
    <button type ="submit">добавить тему</button>
</form>

{% endblock content %}

learning_logs/templates/learning_logs/topic.html
{% extends 'learning_logs/base.html' %}
{% block content%}
<p>Тема: {{topic}}</p>
<p>Записи:</p>
<p>
    <a href="{% url 'learning_logs:new_entry' topic.id %}">add new entry</a>
</p>
<ul>
    {% for entry in entries %}
    <li>
        <p>{{ entry.date_added|date:'M d,Y H:i' }}</p>
        <p>{{ entry.text|linebreaks }}</p>
        <p>
            <a href="{% url 'learning_logs:edit_entry' entry.id %}">Edit entry</a>
        </p>
    </li>
    {% empty %}
    <li>Пока нет записей по этой теме.</li>
    {% endfor %}
</ul>

{% endblock content %}

learning_logs/templates/learning_logs/topics.html
{% extends "Learning_Logs/base.html" %}
{% block content%}
<p>Темы</p>
<ul>
    {% for topic in topics %}
    <li><a href ="{% url 'learning_logs:topic' topic.id %}">{{topic}}</a></li>
    {% empty %}
    <li>Пока не было добавлено ни одной темы.</li>
    {% endfor %}
</ul>

<a href ="{% url 'learning_logs:new_topic' %}">Добавьте новую тему:</a>

{% endblock content %}

users/templates/users/register.html
{% extends "learning_logs/base.html" %}

{% block content %}


<form method="post" action="{% url 'users:register' %}">
    {% csrf_token %}
    {{ form.as_p }}

    <button name="submit">register</button>
    <input type="hidden" name="next"
    value="{% url 'learning_logs:index' %}" />
</form>

{% endblock content %}